spring.application.name=MoneyManagement_BE_SE330

# C?u hình DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/expenseapp
spring.datasource.username=postgres
spring.datasource.password=254263
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# C?u hình Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# C?u hình JWT
jwt.secret=UGF0cmlvdENvbXBsaWNhdGVkU2VjcmV0S2V5QWJvdmVUaGlydHlUd28xMjM0
jwt.expirationMs=86400000
jwt.issuer=money-management-app

# C?u hình Logging
logging.level.root=INFO
logging.level.org.springframework=DEBUG
logging.level.com.expenseapp=DEBUG
logging.file.name=logs/myapp.log